### ISSUE TITLE
Picklist deploy resulting in "Cannot update or delete a picklist while a picklist background job is being executed" error

### ISSUE THREAD

**Issue by petter-eikeland** [flxbl-io/sfp#1]
**Describe the bug**
`"Cannot update or delete a picklist while a picklist background job is being executed"` thrown upon pre picklist deployer (see screenshot below). 

**To Reproduce**
This is an intermittent, but frequent issue (≈ 5–10% of pipeline runs). This occurs when there are multiple picklists to be deployed in the pre deployer. 

**Expected behavior**
When getting `"Cannot update or delete a picklist while a picklist background job is being executed"`, retry the picklist deployment. 

**Screenshots**
![image](https://github.com/dxatscale/sfpowerscripts/assets/97173615/b567a352-a013-4e4d-9cba-5b4811cab882)

**Platform Details (please complete the following information):**
 - OS: Linux
 - Version [e.g. CLI Version  eg: 1.6.6]: 25.5.3 (December 23)
 - Salesforce CLI(sfdx cli) Version: sf version that is on 25.5.3
 - CI Platform: Azure DevOps

**Comment by azlam-abdulsalam** [comment]
@Rocko1204  can you have a look

**Comment by petter-eikeland** [comment]
Sounds good! If the picklist background job is still running after 3 minutes, then it is more a Salesforce issue, than a deployment issue. Thank you for following this up swiftly @Rocko1204 😄

**Comment by dschibster** [comment]
Are one or more of your picklists dependent on one another? This is the issue that made it obvious to me. I handled it by making the deployment of the dependencies a separate step inside the post-folders, while only keeping the values in my package. That resolved the issue for me mostly.
