### ISSUE TITLE
Unable to run npm install -g  @flxbl-io/sfp

### ISSUE THREAD

**Issue by xavier07csm** [flxbl-io/sfp#131]
**Describe the bug**
Unable to run npm install -g  @flxbl-io/sfp

getting error : "npm ERR! notarget No matching version found for @flxbl-io/sfp-logger@^5.0.0."

**To Reproduce**

 run npm install -g  @flxbl-io/sfp

**Expected behavior**

I should not get an error

**Comment by ondrejkratochvil-ext44731** [comment]
Our team is affected as well.

**Comment by azlam-abdulsalam** [comment]
We are looking into it.. Meanwhile if you could use the docker as a workaround

**Comment by azlam-abdulsalam** [comment]
Please switch to v39.0.3 for now until we resolves it

**Comment by azlam-abdulsalam** [comment]
This is fixed in 39.2.3
