### ISSUE TITLE
Quickbuild ignores configured ignore file from sfdx-project.json 

### ISSUE THREAD

**Issue by dschibster** [flxbl-io/sfp#33]
**Describe the bug**

* Using aliasfied packages that are env-specific
* Our sfdx-project json says the following:
```
 "plugins": {
    "sfdx-plugin-prettier": {
      "enabled": false
    },
    "sfpowerscripts": {
      "ignoreFiles": {
        "prepare": ".forceignore",
        "validate": ".forceignore",
        "quickbuild": ".forceignores/.buildignore",
        "build": ".forceignores/.buildignore"
      }
    }
  }
```
* The .buildignore file does not include any src-env-specific packages
* When running quickbuild, one of the aliasfied folders in our standard .forceignore file is ignored, leads to "directory is empty" error as described in this old dx@scale issue here: https://github.com/dxatscale/sfpowerscripts/issues/1083
* Removing the env-specific folder paths from my regular .forceignore file has let the quickbuild finish without issue.

**To Reproduce**
* Run a quickbuild where the package descriptor or content of an env-specific package changed, with those packages being ignored in your standard .forceignore like this: `src-env-specific-alias-post/**`

I am guessing that this is probably more systemic, so other stages would also not take into account any different ignore files.

**Expected behavior**
The `.forceignores/.buildignore` file should be used instead of the standard .forceignore file

**Screenshots**
![image](https://github.com/flxbl-io/sfp/assets/34553908/3ad05006-4e2b-42c0-b05f-7be37eda3abd)

**Platform Details (please complete the following information):**
 - OS: Ubuntu-Latest, Azure DevOps
 - Version: 36.0.10 (Feb 24)
 - npm 18.10.0
 - sfdx-cli as in the container.

**Comment by azlam-abdulsalam** [comment]
@dschibster  can you confirm what are the additional attributes that you have on src-env-specific-alias-post in sfdx-project.json ?

**Comment by dschibster** [comment]
![Screenshot_20240312_004029_Brave](https://github.com/flxbl-io/sfp/assets/34553908/15926a0e-e543-4832-92f9-6746479922d9)

It was working with a previous version of the dx@scale container I should add. After switching to flxbl-io feb24 this error appeared. So this appears to be a regression to me. Or some breaking change occurred I'm unaware of.

**Comment by dschibster** [comment]
@azlam-abdulsalam Regarding the Bug you created, am I correct in the assumption that switching the plugins from "sfpowerscripts" to "sfp" will solve the issue I am currently facing?

**Comment by dschibster** [comment]
Changing the plugin to "sfp" helped resolve this issue. Maybe it makes sense to handle backwards compatibility though :)
