### ISSUE TITLE
Upgrade apex-parser version

### ISSUE THREAD

**Issue by aspagni** [flxbl-io/sfp#36]
**Describe the bug**
It would be great to upgrade the version of apex-parser used by sfp. Current version used is 2.13, but latest apex-parser is 3.6

There are a few new valid apex constructs that are supported by the latest version, but not by the current one (i.e. null coalescing operator)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: 
 - Version [e.g. CLI Version  eg: 1.6.6]
 - Salesforce CLI(sfdx cli) Version:
 - CI Platform: 

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@aspagni  Yes, very much, already was on the radar, as @nawforce has published the new home for apex-parser.

**Comment by azlam-abdulsalam** [comment]
Done
