### ISSUE TITLE
Inconsistency between code and schema (Stage Enum)

### ISSUE THREAD

**Issue by NathanielNizard** [flxbl-io/sfp#38]
**Describe the bug**
Inconsistency for Stage enum
`main/packages/sfpowerscripts-cli/resources/schemas/sfdx-project.schema.json` Stage definition(l. 472) 
doesn't match with :
`packages/sfpowerscripts-cli/src/impl/Stage.ts` (no release symbol)

**To Reproduce**
Check repo

**Expected behavior**
The enum should match with schema definition

**Screenshots**

**Platform Details (please complete the following information):**
 - not platform related

**Additional context**

**Comment by azlam-abdulsalam** [comment]
Thanks @NathanielNizard, will be looking into this

**Comment by dieffrei** [comment]
As mentioned in #98 we can not just add the missing values since ignoreOnStage functionality doesn't support them.
