### ISSUE TITLE
Picklist values not deployed due to error

### ISSUE THREAD

**Issue by ashokkumar14** [flxbl-io/sfp#40]
Added a new value to an existing picklist field. This was not deployed due to error.
`Unable to process pre deploy for Picklist Enabler due to Unable to process Picklist update due to URI malformed`

**To Reproduce**
Add a new value to picklist

**Expected behavior**
New value added to picklist

**Screenshots**
![image](https://github.com/flxbl-io/sfp/assets/13007316/13090003-9ca2-423e-b125-d9a7c63c394b)

**Platform Details (please complete the following information):**
 - OS: all
 - Version [e.g. CLI Version  eg: 1.6.6] 36.0.10
 - CI Platform: Buildkite

**Comment by dieffrei** [comment]
Hi @ashokkumar14 can you confirm if you still have the issue and which SFP version you have installed?

**Comment by dieffrei** [comment]
Closing this issue, feel free to reopen in case you have this issue again.
Thank you
