### ISSUE TITLE
Realese Definition Generate sometimes cannot create the Release-Branch

### ISSUE THREAD

**Issue by Schuchie** [flxbl-io/sfp#42]
**Describe the bug**
The command `sfp releasedefinition:generate` can not always generate the branch including the release definition file. Its not on all of our projects but consistent on one project. I can also reproduce the issue locally in my cli and in the repository.

**To Reproduce**
- Checkout a project and execute the release command:
- `sfp releasedefinition:generate -n release-2.8 -b release-2.8 -d ./release-definitions -f ./release-definitions/release-config.yml -c origin/main`
- Branch gets not created.

**Expected behavior**
Branch including the release definition file was created and pushed.

**Screenshots**
![image](https://github.com/flxbl-io/sfp/assets/18148112/da31d218-bd2e-45ce-adb7-1a657a7a8744)

**Platform Details (please complete the following information):**
 - OS: Linux/MacOs
 - Version [e.g. CLI Version  eg: 1.6.6]: @flxblio/sfp/34.0.2 darwin-arm64 node-v20.6.1
 - Salesforce CLI(sfdx cli) Version: @salesforce/cli/2.30.8 darwin-arm64 node-v20.6.1
 - CI Platform: GitHub

**Additional context**
If I create manually the branch before (empty from main), sfp can create and commit the release definition file.

**Comment by azlam-abdulsalam** [comment]
@Schuchie I am closing this, cant seem to reproduce this one

**Comment by Schuchie** [comment]
@azlam-abdulsalam was for us an edge case and did not happen since then.
