### ISSUE TITLE
sfp container should have community plugin preinstalled

### ISSUE THREAD

**Issue by petter-eikeland** [flxbl-io/sfp#52]
**Describe the bug**
Copying issue from https://github.com/dxatscale/sfpowerscripts/issues/1444

Is it possible to get the community plugin preinstalled in the next release? 😇

[Slack Message](https://flxbl-io.slack.com/archives/CN9N54GF5/p1701682654082599?thread_ts=1701668905.367339&cid=CN9N54GF5)

**To Reproduce**
Try to publish site using `sf community publish -n [MySite] -o [target-org]`

**Expected behavior**
`sf community publish` command takes 2-4 seconds to execute as sf community plugin is preinstalled

**Expected behavior**
`sf community publish` command takes 3 minutes to execute as sf community plugin is not preinstalled

**Comment by dieffrei** [comment]
Hi @petter-eikeland, we want to keep this standard docker image as lightweight as possible. That is why this plugin is not installed automatically on SF CLi either.
(https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_plugins_overview.htm)
For this case, I advice you to create a custom image.
If you need help with that, let me know!
CC: @azlam-abdulsalam
