### ISSUE TITLE
Enhancement: dependency:install add a filter based on releasedefinition

### ISSUE THREAD

**Issue by alanjaouen** [flxbl-io/sfp#55]
As (almost) all commands allow to filter on releasedefinition file, It will be helpfull to have this filter on dependency:install too

recreating from https://github.com/dxatscale/sfpowerscripts/issues/1445, as I thinks it's still pertinent

**Comment by dieffrei** [comment]
Issue solved on #108.
It will be available in the next release.
Thank you for your contribution @alanjaouen
