### ISSUE TITLE
--disableartifactupdate deprecated?

### ISSUE THREAD

**Issue by ludvig-ravelin** [flxbl-io/sfp#57]
**Describe the bug**
I am using the script "sfp validate pool --disableartifactupdate" in a pipeline on Gitlab, the pipeline and it fails. It complains that the flag is deprecated.

**To Reproduce**
Steps to reproduce the behavior: Try to run the following script in a pipeline on Gitlab, not sure what it will say on Github.

**Expected behavior**

Warning: disableartifactupdate flag is deprecated, Artifacts used for 
 ›   validation are never recorded in the org 

**Screenshots**

**Platform Details (please complete the following information):**
 - OS: whatever OS this image is using: ghcr.io/flxbl-io/sfp:latest
 - Version [e.g. CLI Version  eg: 1.6.6]
 - Salesforce CLI(sfdx cli) Version:
 - CI Platform: Gitlab

**Additional context**

**Comment by dieffrei** [comment]
Hi @ludvig-ravelin yes it was deprecated in the last release. Because the artifact information never is updated.
Are you re-using those scratch orgs after validation? Why would you need that information in the scratch org?

**Comment by dieffrei** [comment]
@ludvig-ravelin I'm closing this issue since it was already answered.
Let us know if we can do anything else.
