### ISSUE TITLE
release: Permission Set Group status check not recognizing previously triggered PSG update

### ISSUE THREAD

**Issue by dschibster** [flxbl-io/sfp#60]
**Describe the bug**
Two source packages that are deployed one after the other affect the same permission set in a permission set group. The second package seems to check if any permission set groups are being updated, which the cli tells me no.
Continuing to deploy the second package, I get the error message that the PSG that the aliasfied permission set belongs to is being updated and to check back later.

**To Reproduce**
Order two source-packages one after the other, have the first one contain an empty permission set that is part of a bigger PSG. Have the second one contain access to external and named credentials that are org-specific. Have both of them as part of a release-definition to release to any org.

**Expected behavior**
The CLI should wait until the PSG is done updating.

**Screenshots**

![image](https://github.com/flxbl-io/sfp/assets/34553908/eb661956-9d33-4970-8af7-4df547fa9b25)

**Platform Details (please complete the following information):**
flxbl-io/sfp:latest

**Additional context**
Does the CLI only check on PSGs that are part of the package - so do I need to add the PSG to the second source package so that the 'updating' part will get recognized?

**Comment by dieffrei** [comment]
@dschibster SFP doesn't check only the PermissionSetGroups that belong to the package; it also checks if any PermissionSetGroup in the organization has been updated.
`SELECT Id,MasterLabel,Status FROM PermissionSetGroup WHERE Status = 'Updating'`.
Any thoughts @azlam-abdulsalam?

**Comment by dschibster** [comment]
@dieffrei That makes it even stranger then. :)

**Comment by dieffrei** [comment]
@dschibster can you check if immediately after the deployment of the first package the PSG recalculation started?
The PSG recalculation is asynchronous maybe, it is taking more time than usual to begin to recalculate.
How frequent is this issue?

**Comment by dschibster** [comment]
![image](https://github.com/flxbl-io/sfp/assets/34553908/462b2710-1ec2-43d7-b384-ebef0cb1e0d9)
I waited for an answer until my next release and this time, it found the updating PSG.

Could it be that the PSG update started after the query was executed? That could explain the lack of waiting the first time I ran the release.

**Comment by dieffrei** [comment]
@dschibster I will close this issue, if it happens again, let us know!
