### ISSUE TITLE
SFP does not support deployments of the newest SF AI features

### ISSUE THREAD

**Issue by domrycz** [flxbl-io/sfp#72]
**Describe the bug**
The latest sfp docker image has version 2.25.7 of SF CLI and this version does not support features related to Prompt Builder. For example GenAiPromptTemplate metadata or InvocableMethod capabilityType modifiers.

**To Reproduce**

**Expected behavior**
I can deploy the apex methods which are called by Prompt Templates (I can do it in SF CLI version 2.27.6)

**Screenshots**

**Platform Details (please complete the following information):**
 - docker image: ghcr.io/flxbl-io/sfp:38.4.1-8749491772
 - Salesforce CLI(sfdx cli) Version: 2.25.7
 - CI Platform: Gitlab CI

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@domrycz  sfp no longer depends on sf cli. It is tied to the underlying libraries used. We are working on a feature that upgrades libraries to v8 and you can see here
https://github.com/flxbl-io/sfp/pull/71
