### ISSUE TITLE
Managed package installation fails in CI pipeline, subscriber package errors

### ISSUE THREAD

**Issue by dschibster** [flxbl-io/sfp#74]
Sorry for the double report, I want to use my Salesforce-centric GitHub account for this and forgot to switch accounts.

**Describe the bug**
@dieffrei referring to the Slack thread, this is the issue I mean.
Using the latest vlocity_cmt package (04t5c000001WQ1GAAW) leads to unforeseen errors when trying to install it on a scratch org using the sfp validate command.

It returns the following error
![image](https://github.com/flxbl-io/sfp/assets/106119828/94d68d80-2a95-4871-beb1-5391c7d8dca4)

Manual installs using the very same package Id works on a scratch org when utilizing the sf command.

**To Reproduce**
Create a CI scratch Org, run a validation that depends on vlocity_cmt being installed.

**Expected behavior**
The package should get installed

**Screenshots**
See above.

**Platform Details (please complete the following information):**
Latest ghcr container, Azure DevOps.

**Additional context**
Wasn't able to find anything wrong in my repository as I am able to install the package very easily when using the sf command, it fails in sfp commands exclusively.

**Comment by azlam-abdulsalam** [comment]
@dschibster  is this on an existing org with a previous version of the vlocity_cmt  package installed or a fresh install

**Comment by dschibster** [comment]
This is on an existing Org. Basically the artifact had another dependency so installed an earlier version. Installation of the new one leads to this error when the dependency is updated

**Comment by dieffrei** [comment]
Hey @dschibster I could reproduce the error, It might be fixed in the upgrade that we are working on.
I keep you posted, going to test in the latest release lib.
CC: @azlam-abdulsalam

**Comment by dieffrei** [comment]
Updating the library I got (last updates from salesforce cli packaging library they updated exactly this error handling part):

```
Unable to install vlocity  in flxbl-dev@xxxx.com due to Installation key not valid. Enter the correct package installation key and try again.: Password
    FIELD_INTEGRITY_EXCEPTION: Installation key not valid. Enter the correct 
    package installation key and try again.: Password
```
I also tried to install using "sf cli" it also didn't work.

Did you setup the keys? @dschibster

**Comment by dschibster** [comment]
Hate to say that we weren't given keys. It seems like for follow up versions of the package they newly started utilizing keys. I would have to ask Salesforce if there is a way to get it, otherwise we would have to fixate the dependency.

**Comment by dschibster** [comment]
Thing is that the package has an automatic update process, so I'm guessing they started using keys internally

**Comment by dschibster** [comment]
Closing the issue because by now it's obviously not on sfp anymore. I'll see if I'm able to get an installation key. Thanks @dieffrei!
