### ISSUE TITLE
sfp metrics report showing help command output all the time

### ISSUE THREAD

**Issue by bill-sutton-coinbase** [flxbl-io/sfp#90]
**Describe the bug**
No matter the flags I use I am alway getting the output of `sfp metrics report --help` instead of anything else.

**To Reproduce**
run `sfp metrics report -m sfpowerscripts.package.created -t counter`

**Expected behavior**
I would expect either an error and success message

**Screenshots**
![image](https://github.com/flxbl-io/sfp/assets/107077866/f2d96c35-2ebc-4e11-a826-f31b2a84fb15)

**Platform Details (please complete the following information):**
 - OS: MAC OS
 - Version @flxblio/sfp/30.3.4 darwin-arm64 node-v22.3.0
 - Salesforce CLI(sfdx cli) Version: @salesforce/cli/2.47.6 darwin-arm64 node-v20.14.0
 - CI Platform: NA (Running SFP Locally)

**Additional context**

**Comment by azlam-abdulsalam** [comment]
@bill-sutton-coinbase The metric should be used with quotes, otherwise, this results in oclif interpreting as an argument, causing the help to be displayed
