### ISSUE TITLE
sfp validate org command deploys the package expected to only validate

### ISSUE THREAD

**Issue by GaneshSMC** [flxbl-io/sfp#94]
We have been utilizing sfp to setup an CI process in our workflow we have the following command
**sfp validateAgainstOrg -o DEV_SB -v DEV_SB --basebranch=origin/main --diffcheck --coveragepercent 95  --mode=fastfeedback**
this command deploys the package

Expected behaviour:
we expect only to validate not to deploy the package/components

Documents Screenshots:
![image](https://github.com/user-attachments/assets/dcce7618-95a8-408a-ba7e-059ab2fe36ef)
![image](https://github.com/user-attachments/assets/d3c8a7e0-e95d-4881-ba99-55c377e4c402)
From these document on our understanding the sfp document says validate is utilized to validate a change also further it says it will validate by deploying.

We utilized to it expecting that it will only validate against our target dev org but its deploying the package even though any apex test fails.

Validate Test - with Apex test passed
![image](https://github.com/user-attachments/assets/2aa6fa5d-459d-4722-8d2a-e2f872a0d300)
Validate test - with Apex test failed
![image](https://github.com/user-attachments/assets/228cc7f5-c36c-4dc2-9a6a-a8cd6e24c96f)

On both the case the package gets deployed.
We expect only to validate not to deploy the package/components.
We aren't clear about what's the actual behaviour of sfp validate org command.
Could you clarify about this to us!

**Comment by dieffrei** [comment]
Hi @GaneshSMC the command works the same as scratch org pooling validation, the code/metadata is deployed (it doesn't use the only-validation traditional flag).
There is no support to "only validate" deployment on SFP.
